export const routes = {
  home: "/",
  register: "/register",
  signIn: "/sign-in",
  app: "/app",
  onboarding: "/app/onboarding",
  family: "/app/family",
  familyInvites: "/app/family/invites",
  sources: "/app/sources",
  reminders: "/app/reminders",
  settings: "/app/settings",
  settingsSecurity: "/app/settings/security",
  settingsData: "/app/settings/data",
  profile: (profileId: string) => `/app/profile/${profileId}`,
  carePlan: (profileId: string) => `/app/profile/${profileId}/care-plan`,
  timeline: (profileId: string) => `/app/profile/${profileId}/timeline`,
  calendar: (profileId: string) => `/app/profile/${profileId}/calendar`,
  records: (profileId: string) => `/app/profile/${profileId}/records`,
  backfill: (profileId: string) => `/app/profile/${profileId}/records/backfill`,
  importRecords: (profileId: string) => `/app/profile/${profileId}/records/import`,
  medications: (profileId: string) => `/app/profile/${profileId}/medications`,
  visitPrep: (profileId: string) => `/app/profile/${profileId}/visit-prep`,
  sharing: (profileId: string) => `/app/profile/${profileId}/sharing`,
} as const;

export const staticRouteValues = [
  routes.home,
  routes.register,
  routes.signIn,
  routes.app,
  routes.onboarding,
  routes.family,
  routes.familyInvites,
  routes.sources,
  routes.reminders,
  routes.settings,
  routes.settingsSecurity,
  routes.settingsData,
] as const;
