import { afterEach, describe, expect, it, vi } from "vitest";

import type { VisitPrepData, VisitPrepSectionSelection } from "./visit-prep-types";
import { buildVisitPrepSummary, copyPlainText } from "./visit-prep-utils";

const data: VisitPrepData = {
  profileName: "Alex",
  age: 46,
  generatedOn: "July 21, 2026",
  appointments: [
    {
      title: "Primary care visit",
      timing: "Tuesday, July 28, 2026 at 9:30 AM PDT until 10:15 AM PDT",
      timezone: "America/Los_Angeles",
      location: "Downtown clinic",
    },
    {
      title: "Follow-up visit",
      timing: "Friday, August 14, 2026 at 2:00 PM PDT",
      timezone: "America/Los_Angeles",
      location: null,
    },
  ],
  medications: ["Medication one"],
  conditions: ["Condition one"],
  attention: ["Due item"],
  thisYear: ["Later item"],
  unknown: ["Unknown item"],
  discussion: ["Discussion item"],
  clinician: ["Clinician instruction"],
  recentEvents: ["Service · Method: Abnormal result recorded · Jun 2026. No interpretation added."],
  personalNotes: ["Ask about travel timing."],
  sourceLinks: [{ label: "Reviewed guidance", url: "https://example.test/guidance" }],
  suggestedQuestions: [],
};

const sections: VisitPrepSectionSelection = {
  appointments: true,
  medications: true,
  conditions: true,
  attention: true,
  thisYear: true,
  unknown: true,
  discussion: true,
  clinician: true,
  recentEvents: true,
  personalNotes: true,
};

const originalExecCommand = Object.getOwnPropertyDescriptor(document, "execCommand");

afterEach(() => {
  vi.restoreAllMocks();
  if (originalExecCommand === undefined) {
    Reflect.deleteProperty(document, "execCommand");
  } else {
    Object.defineProperty(document, "execCommand", originalExecCommand);
  }
});

describe("buildVisitPrepSummary", () => {
  it("builds concise plain text with exact appointment and neutral result labels", () => {
    const summary = buildVisitPrepSummary(data, "concise", sections, ["What should we discuss?"]);

    expect(summary).toContain(
      "Primary care visit — Tuesday, July 28, 2026 at 9:30 AM PDT until 10:15 AM PDT — Downtown clinic (America/Los_Angeles)",
    );
    expect(summary).not.toContain("Follow-up visit");
    expect(summary).toContain("Concise format omits 1 additional item");
    expect(summary).toContain("Major conditions\n- Condition one");
    expect(summary).toContain(
      "Recent abnormal or inconclusive records\n- Service · Method: Abnormal result recorded · Jun 2026. No interpretation added.",
    );
    expect(summary).not.toContain("|");
    expect(summary).toContain("Personal notes\n- Ask about travel timing.");
    expect(summary).toContain("Reviewed guidance: https://example.test/guidance");
    expect(summary).toMatch(/Generated by CareCadence\..*does not replace clinical advice\.$/s);
  });

  it("includes all appointments in extended mode and honors excluded sections", () => {
    const summary = buildVisitPrepSummary(
      data,
      "extended",
      { ...sections, medications: false },
      [],
    );

    expect(summary).toContain("Primary care visit");
    expect(summary).toContain("Follow-up visit");
    expect(summary).not.toContain("Current medications");
  });

  it("keeps every explicitly ordered question in the concise agenda", () => {
    const questions = ["One?", "Two?", "Three?", "Four?", "Five?"];
    const summary = buildVisitPrepSummary(data, "concise", sections, questions);

    for (const question of questions) expect(summary).toContain(`- ${question}`);
    expect(summary).not.toMatch(/omits .*question/i);
  });
});

describe("copyPlainText", () => {
  it("uses the Clipboard API when it is allowed", async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);

    await expect(copyPlainText("private summary", { clipboard: { writeText } })).resolves.toBe(
      "clipboard",
    );
    expect(writeText).toHaveBeenCalledWith("private summary");
  });

  it("falls back to a temporary textarea and cleans it up", async () => {
    const writeText = vi.fn().mockRejectedValue(new Error("Denied"));
    const execCommand = vi.fn().mockReturnValue(true);
    Object.defineProperty(document, "execCommand", {
      configurable: true,
      value: execCommand,
    });

    await expect(
      copyPlainText("private summary", { clipboard: { writeText }, document }),
    ).resolves.toBe("fallback");
    expect(execCommand).toHaveBeenCalledWith("copy");
    expect(document.querySelector("textarea")).not.toBeInTheDocument();
  });

  it("rejects when neither browser copy method succeeds", async () => {
    Object.defineProperty(document, "execCommand", {
      configurable: true,
      value: vi.fn().mockReturnValue(false),
    });

    await expect(
      copyPlainText("private summary", {
        clipboard: { writeText: vi.fn().mockRejectedValue(new Error("Denied")) },
        document,
      }),
    ).rejects.toThrow("did not allow");
    expect(document.querySelector("textarea")).not.toBeInTheDocument();
  });
});
